spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hn.user.entity
  configuration:
    map-underscore-to-camel-case: true
apiPath: /api/v1

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'user'
      paths-to-match: '/**'
      packages-to-scan: com.hn.user.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn