spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: service-user
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hn.user.domain.entity
  configuration:
    map-underscore-to-camel-case: true

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hn.user.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    enable-dynamic-parameter: true
    language: zh_cn
    enable-filter-multipart-apis: true
    enable-filter-multipart-api-method-type: POST
server:
  servlet:
    context-path: /api/user