server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_db?serverTimezone=UTC
    username: user
    password: user
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8