spring:
  cloud:
    gateway:
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: service-jd-store
          uri: lb://service-jd-store
          predicates:
            - Path=/api/jdstore/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  application:
    name: gateway
server:
  port: 8888
  #servlet:
    #context-path: /api
