spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: service-jd-store
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
server:
  servlet:
    context-path: /jdstore
knife4j:
  enable: true
  setting:
    enable-dynamic-parameter: true
    language: zh_cn
    enable-filter-multipart-apis: true
    enable-filter-multipart-api-method-type: POST